### ISSUE TITLE
Is this extension dead?

### ISSUE THREAD

**Issue by nmn** [habovh/nova-flow#1]

**Comment by habovh** [comment]
Hi @nmn, the extension is most definitely not dead. Basic features like error reporting were the minimum required for a working workflow so I haven’t allocated much time to this extension since then.

Are you encountering issues? Are you requesting a feature? In any case, PRs are welcome!

**Comment by habovh** [comment]
@nmn I'm going to go ahead and close this issue since there isn't really much value in keeping this open. Feel free to open a discussion or another issue, or submit a PR if you'd like to see some changes with this extension.

**Comment by nmn** [comment]
I have been seeing sporadic problems in getting even error reporting to work, but I'll do more testing and report back.
