### ISSUE TITLE
Hover info

### ISSUE THREAD

**Issue by jefflewis** [habovh/nova-flow#2]
Provide hover info for types.

**Comment by jefflewis** [comment]
I'd be willing to take a stab at this, but I honestly don't really know _where_ to start for this.

**Comment by habovh** [comment]
Hi @jefflewis, hover info should be working, but it's pretty minimal with currently no color highlighting. Can you provide a sample project/file where the hover functionality does not work?

**Comment by jefflewis** [comment]
Well I dug into this a bit more. It seems like the extension doesn't start on launch. And if I manually restart it, it just logs `activating`.

![CleanShot 2021-04-22 at 09 47 03@2x](https://user-images.githubusercontent.com/4528172/115725309-bb985a80-a34f-11eb-9800-99a98e0e3e15.png)

Here's a sample repo where I get nothing from this extention: https://github.com/jefflewis/nova-flow-test

**Comment by nmn** [comment]
I can confirm that the extension tends to not start on launch, but for me it does work after manually restarting the server, and the clicking restart again in the in-app notification about the Flow Server.

**Comment by habovh** [comment]
Thanks to both of you for the report, I’ll dig into this today and hopefully release an update addressing this issue!

**Comment by habovh** [comment]
I've released version 0.3, please let me know if you still encounter issues! In any case, many thanks for the repro repo @jefflewis! It helped me notice I based the extension on one of my non-standard project using `flowconfig.json` instead of `.flowconfig` configuration file. Automatic activation was based on the presence of this non standard file only.

**Comment by habovh** [comment]
@jefflewis I hope you don’t mind that I used your repro repo for the screenshots in the new 0.3.1 readme 🤓

**Comment by jefflewis** [comment]
@habovh Not at all! Glad it could help!
