### ISSUE TITLE
Request: activity indicator

### ISSUE THREAD

**Issue by richardvenneman** [habovh/nova-flow#4]
Hi,

Thanks for the great plugin! When working in larger repositories it's sometimes hard to figure out if Flow is working. What helps is to open the Activity Indicator and look for the Flow process.

I just saw that VS Code shows a progress indicator. I couldn't immediately find a method to display a progress bar in https://docs.nova.app/, but it would be great if something similar could be shown.

<img width="219" alt="Screenshot 2022-10-31 at 09 28 55" src="https://user-images.githubusercontent.com/75705/198965735-b3fcd90e-682e-4aa9-af2b-c500fd056499.png">

**Comment by habovh** [comment]
Hey @richardvenneman, thanks for the suggestion! I just implemented a basic information sidebar and released an update, I hope you'll find it useful!
